### PR TITLE
Improved mobile view

### PR DESCRIPTION
**Pull request by ghost**
- Fixed padding for #public section
- Made the public key and code tag break when screen is too small to display it in one line
- Made public key selectable on click
- Removed burger menu as it doesn't do anything on mobile view
- Removed extra '"' which was breaking html formatting
- Removed extra ':' from copy

### CODE REVIEW

**Comment by hackergrrl** [comment]
@cblgh do you have a phone you could review this with?

@oraklu could you share a screenshot?

**Comment by ghost** [comment]
Sure, here yo go:

cabal-to

**Comment by hackergrrl** [comment]
:+1:

**Comment by hackergrrl** [comment]
If you can fix the conflicts I'll merge it in

**Comment by ghost** [comment]
Done - the issue was with some copy which changed in the meantime

**Comment by hackergrrl** [comment]
Many thanks @oraklu for these improvements :pray:

**Comment by ghost** [comment]
You're welcome!

**Comment by cblgh** [comment]
@noffle sorry i was offline for a while there, looks great tho thanks @oraklu :3

**Pull request merged**
