### PR TITLE
Add links to fediverse and web feed

### LINKED ISSUE #15: Please add Mastodon account
Please add Mastodon account from which we can receive news about [Cabal](https://mastodon.social/@cabal).

### PR DESCRIPTION
**Pull request by sjehuda**
including auto-detection. Fixes #15 #16

### CODE REVIEW

**Comment by hackergrrl** [comment]
I'm not sure if anyone has the capacity + interest in maintaining a social media feed for Cabal. It Closing this for now. Let's see if anyone has interest+capacity first on #15.

**Comment by sjehuda** [comment]
I just want want a news channel from which I can get updates.
I can use the release feed of git but I rather not to.

**Comment by hackergrrl** [comment]
@sjehuda I understand your desire for updates, *and* keeping an additional feed updated with said updates is labour on the part of the cabal team that we may not have capacity for right now.

**Comment by sjehuda** [comment]
Then you can use https://github.com/cabal-club/cable/releases.atom
This feed is updated upon release change.

**Comment by sjehuda** [comment]
> @sjehuda I understand your desire for updates, and keeping an additional feed updated with said updates is labour on the part of the cabal team that we may not have capacity for right now.

Did you ask at the Cabal group for volunteers?

**Comment by hackergrrl** [comment]
> Did you ask at the Cabal group for volunteers?

No, nor is that one of my responsibilities. The people working on this project do so as volunteers, and choose for themselves where and if they put in time & effort. You may be disappointed if you have expectations of us doing the labour of your choosing. Please stop.

If **you** wish to run or search for volunteers to maintain a social media feed of cabal updates, please feel free to do so.

**Pull request closed without merging**
