### PR TITLE
Replaced the blurry logo with a vector. Aligned with the right-hand side of the header.

### PR DESCRIPTION
**Pull request by neauoire**

### CODE REVIEW

**Comment by neauoire** [comment]
Fixed blurry logo on retina.

screen shot 2018-08-07 at 9 40 31 am

**Comment by neauoire** [comment]
screen shot 2018-08-07 at 9 40 06 am

Scaled logo to v-align with right-hand side button.

screen shot 2018-08-07 at 9 40 22 am

**Comment by neauoire** [comment]
Improved readability of the quickstart guide, and made the *public cabal* hash more obvious.

screen shot 2018-08-07 at 10 14 20 am

**Comment by hackergrrl** [comment]
Slick! Thank you @neauoire :tada:

**Comment by neauoire** [comment]
I had to remove the leading `/` in the index for the css to work locally, can you double-check that this doesn't break GitHub page?

**Comment by cblgh** [comment]
🙌

**Pull request merged**
